# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c927978986c35d67a78dd8ed24c40e8f9561fa7646fcb30cfbaa5d490d39d5886f23105bc642ad64c3f249a8b6d6abf08b74838f6d1ac11828d1f7c36a53777a

test:
  secret_key_base: f5c4b6f5ecab1e96e98b4960d646264583dcd630513c36c30f60d36f2f0d11b2a373627229114da523c3e8479e516bc3c4febf2f7bcc19a25db8ba810ec42a58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
